[2021-12-06 11:29:09,270] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.Feature_Scaling scheduled__2021-12-05T00:00:00+00:00 [queued]>
[2021-12-06 11:29:09,277] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: brent_pricing_dag.Feature_Scaling scheduled__2021-12-05T00:00:00+00:00 [queued]>
[2021-12-06 11:29:09,277] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 11:29:09,277] {taskinstance.py:1242} INFO - Starting attempt 1 of 3
[2021-12-06 11:29:09,277] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-06 11:29:09,284] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): Feature_Scaling> on 2021-12-05 00:00:00+00:00
[2021-12-06 11:29:09,287] {standard_task_runner.py:52} INFO - Started process 12751 to run task
[2021-12-06 11:29:09,293] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'brent_pricing_dag', 'Feature_Scaling', 'scheduled__2021-12-05T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_brent_pricing.py', '--cfg-path', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmpmqfelczc', '--error-file', '/var/folders/b3/j_ybgjv53p33dy62wlktdr4m0000gp/T/tmp8o85ofyt']
[2021-12-06 11:29:09,295] {standard_task_runner.py:77} INFO - Job 25: Subtask Feature_Scaling
[2021-12-06 11:29:14,329] {logging_mixin.py:109} INFO - Running <TaskInstance: brent_pricing_dag.Feature_Scaling scheduled__2021-12-05T00:00:00+00:00 [running]> on host zipcodes-MacBook-Pro-3.local
[2021-12-06 11:29:19,362] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=keerthiballa@gmail.com
AIRFLOW_CTX_DAG_OWNER=kballa
AIRFLOW_CTX_DAG_ID=brent_pricing_dag
AIRFLOW_CTX_TASK_ID=Feature_Scaling
AIRFLOW_CTX_EXECUTION_DATE=2021-12-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-05T00:00:00+00:00
[2021-12-06 11:29:19,364] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: feature_scaling() missing 2 required positional arguments: 'x_train' and 'y_train'
[2021-12-06 11:29:19,378] {taskinstance.py:1270} INFO - Marking task as UP_FOR_RETRY. dag_id=brent_pricing_dag, task_id=Feature_Scaling, execution_date=20211205T000000, start_date=20211206T162909, end_date=20211206T162919
[2021-12-06 11:29:19,405] {standard_task_runner.py:88} ERROR - Failed to execute job 25 for task Feature_Scaling
Traceback (most recent call last):
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/Users/ballakeerthi/opt/anaconda3/envs/airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: feature_scaling() missing 2 required positional arguments: 'x_train' and 'y_train'
[2021-12-06 11:29:19,440] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-06 11:29:19,457] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
